# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exfinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_devolucion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_prestamo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
