# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exfinal', '0002_auto_20161118_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='ISBN',
            field=models.CharField(max_length=13),
        ),
    ]
