# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exfinal', '0004_auto_20161118_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Dpi',
            field=models.CharField(max_length=13),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Libros',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Libros',
            field=models.ManyToManyField(through='exfinal.Prestamo', to='exfinal.Libros'),
        ),
    ]
